# Generated by Django 5.0.7 on 2025-10-15 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cliente', models.CharField(max_length=50)),
                ('servicio', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('barbero', models.CharField(max_length=50)),
            ],
        ),
    ]
