# Generated by Django 5.0.7 on 2025-12-21 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosDiarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, unique=True)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ingreso Diario',
                'verbose_name_plural': 'Ingresos Diarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
